# FROM tggolangbot:staging
FROM shoutertm/dockerhub:tggolangbot AS builder
WORKDIR /go/src/tg_golang_bot
COPY . .
RUN CGO_ENABLED=0 go build -gcflags "all=-N -l" -o /go/bin/tg_golang_bot -v ./cmd/app/main.go
CMD [ "/go/bin/dlv", "--listen=:12345", "--headless=true", "--log=true", "--log-output=debugger,debuglineerr,gdbwire,lldbout,rpc", "--accept-multiclient", "--api-version=2", "exec", "/go/bin/tg_golang_bot" ] 