version: '3.5'

volumes:
  pgdata:
  
services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./deployments/:/docker-entrypoint-initdb.d/
      
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  bot:
    depends_on:
      - db
    image: tggolangbot
    environment:
      CREATE_TABLE: "yes"
      DB_SWITCH: "on"
      TOKEN: 7125415904:AAEy8G3UeKuLcABGT6Ouh_gWgp0JVPhetCY
      API_CMC: 90671ff9-f380-42ae-8b16-fa7886d55fe9
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: test
      DBNAME: postgres
      SSLMODE: disable
      LANGUAGE: en
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000